---
title: "Task 6"
author: "Claire Hays"
date: "9/13/2022"
output: 
  html_document:
    theme: cosmo
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load packages
```{r}

library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
library(lubridate)


```


```{r}

head(iris)
mutate(iris, 'Label')

large_petal_width <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Width)) == 1) %>%
  mutate(Label = 'Largest Petal Width')
large_petal_length <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Length)) == 1) %>%
  mutate(Label = 'Largest Petal Length')


ggplot(data = iris, mapping = aes(x = Sepal.Length, 
                                  y = Sepal.Width)) +
  geom_point(aes(color = Species, shape = Species)) +
    geom_point(size = 3, shape = 1, color = "black", data = large_petal_length) +
    geom_point(size = 3, shape = 1, color = "black", data = large_petal_width) +
  geom_text(aes(color = Species, label = Label), nudge_y=-.1, data = large_petal_length) +
  geom_text(aes(color = Species, label = Label), nudge_y=.1, data = large_petal_width) +
  labs(x = "Sepal Length (cm)",
       y = "Sepal Width (cm)",
       title = "Different Iris Species Have Different Sepal",
       subtitle = "The Largest Petal Sizes For Each Species Do Not Correspond To The Largest") + 
  theme(legend.position = "bottom")

```

Scrabble visual (dowloading the file)
```{r}

download.file("https://github.com/fivethirtyeight/data/raw/master/scrabble-games/scrabble_games.csv", "Scrabble")
scrabble_dat <- read_csv("Scrabble")
head(scrabble_dat)


ScrabbleAll <- scrabble_dat %>%
  select(date, winnerscore, loserscore) %>%
  pivot_longer(c("winnerscore","loserscore"), names_to = "win-loss", values_to = "score") %>%
  filter(score > 0) %>%
  mutate(year = year(date),
         week = week(date)
  )

head(ScrabbleAll)

```


Add the average score, average score before AND after the addition of 11,000 words
```{r}

average_score <- ScrabbleAll %>%
  group_by(year, week) %>%
  summarise(avgscore = mean(score), Date = min(date))
head(average_score)
tail(average_score)

before_add_avg <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date <= as.Date("2006-03-01")) %>%
  summarise(avglength = mean (score), Date = min(date))
head(before_add_avg)


after_add_avg <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date > as.Date("2006-03-01")) %>%
  summarise(avglength = mean (score), Date = min(date))
head(after_add_avg)

```

Recreate the graph
```{r}

ggplot(data = average_score, mapping = aes(x= Date, y = avgscore)) +
  geom_point() +
  geom_smooth(data = before_add_avg, method = "lm", color = "Orange") +
  annotate("text", x=as.Date("2005-12-01"), y=380, label="Trend Before", size=5, color="orange") +
  geom_smooth(data = after_add_avg, method = "lm", color = "Blue") +
  annotate("text", x=as.Date("2006-07-15"), y=380, label="Trend After", size=5, color="blue") +
  geom_vline(xintercept = as.Date("2006-03-01"), linetype = 2) +
  labs(x = " ", y = "Average Score", title = "Scrabble scores in the age of 'QI' and 'ZA'", subtitle = "Weekly average scores before and after the addition of around 11,000 words to the Scrabble dictionary", caption = "Source: FiveThirtyEight") +
  annotate("text", x = as.Date("2006-03-01"), y = 390, label = "Dictionary\nupdated", size = 4) +
  scale_x_date(date_labels = "%b %y'") +
  theme_bw()

```


everything for graph 2 in one code chunk:
```{r}

download.file("https://github.com/fivethirtyeight/data/raw/master/scrabble-games/scrabble_games.csv", "Scrabble")
scrabble_dat <- read_csv("Scrabble")
head(scrabble_dat)


ScrabbleAll <- scrabble_dat %>%
  select(date, winnerscore, loserscore) %>%
  pivot_longer(c("winnerscore","loserscore"), names_to = "win-loss", values_to = "score") %>%
  filter(score > 0) %>%
  mutate(year = year(date),
         week = week(date)
  )

head(ScrabbleAll)

average_score <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date > as.Date"2005-06-01" & Date < as.Date"2006-12-1") %>%
  summarise(avgscore = mean(score), Date = min(date))
head(average_score)
tail(average_score)

before_add_avg <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date <= as.Date("2006-03-01")) %>%
  summarise(avglength = mean (score), Date = min(date))
head(before_add_avg)


after_add_avg <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date > as.Date("2006-03-01")) %>%
  summarise(avglength = mean (score), Date = min(date))
head(after_add_avg)


ggplot(data = average_score, mapping = aes(x= Date, y = avgscore)) +
  geom_point() +
  geom_smooth(data = before_add_avg, method = "lm", color = "Orange") +
  annotate("text", x=as.Date("2005-12-01"), y=380, label="Trend Before", size=5, color="orange") +
  geom_smooth(data = after_add_avg, method = "lm", color = "Blue") +
  annotate("text", x=as.Date("2006-07-01"), y=380, label="Trend After", size=5, color="blue") +
  geom_vline(xintercept = as.Date("2006-03-01"), linetype = 2) +
  labs(x = " ", y = "Average Score", title = "Scrabble scores in the age of 'QI' and 'ZA'", subtitle = "Weekly average scores before and after the addition of around 11,000 words to the Scrabble dictionary", caption = "Source: FiveThirtyEight") +
  annotate("text", x = as.Date("2006-03-01"), y = 390, label = "Dictionary\nupdated", size = 4) +
  scale_x_date(date_labels = "%b %y'") +
  theme_bw()

```

