---
title: "Task 14"
author: "Claire Hays"
date: "10/18/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
library(lubridate)
library(ggplot2)
library(grid)
library(corrplot)
library(COR)
library(readr) 
library(haven)
library(readxl)
library(foreign)
library(stringr)
library(stringi)

```

```{r download dat}
download.file("https://github.com/WJC-Data-Science/DTS350/raw/master/bible.csv", "bible_data")
bible_dat <- read.csv("bible_data")
```

```{r just OT and just NT}

old_test <- bible_dat %>%
  filter(volume_title == "Old Testament") %>%
  select(scripture_text)


new_test <- bible_dat %>%
  filter(volume_title == "New Testament") %>%
  select(scripture_text)


```

```{r verse length function and averages}

verse_length_f <- function(df) {
  words <- vector("integer", 0)
  for (i in df) {words <- append(words, str_length(i))}
  words
}
  
mean(verse_length_f(old_test))
mean(verse_length_f(new_test))

```

```{r Lord/lord frequency}

str_count(old_test, "(?i)lord")
str_count(new_test, "(?i)lord")
```

```{r visualization}

new_test_words <- bible_dat %>%
  filter(volume_title == "New Testament") %>%
  select(book_title, verse_id, scripture_text) %>%
  group_by(book_title) %>%
  mutate(words = str_count(scripture_text, '\\w+'))



question_3 <- ggplot(new_test_words, aes(x = book_title, y = mean(words))) +
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Avg Words in A Verse",
       subtitle = "Per chapter of the New Testament",
       x = "Book",
       y = "Avg Words per Verse")

question_3
```

There are more words per verse in the old testament vs new testament and the word Lord/lord is used much more frequently in the old testament.  Several of the gospels of the new testament have a higher avg words per verse than other chapters of the new testament. (specifically chapters Matthew, Mark, Luke, and John.)
