---
title: "Case Study 3"
author: "Claire Hays"
date: "9/12/2022"
output: 
  html_document:
    theme: cosmo
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
library(gapminder)
```

First graph
```{r}

dat <- filter(gapminder, country != "Kuwait")
head(dat)

ggplot(data = dat) +
  geom_point(mapping = aes(x = lifeExp, y = gdpPercap, color = continent, size = pop)) +
  facet_wrap(~ year, nrow = 1) +
  scale_y_continuous(trans = "sqrt") +
  scale_size_continuous(name = "Population (100k)") +
  xlab("Life Expectancy") +
  ylab("GDP per capita") +
  theme_bw()

```


create a weighted mean and then the second graph
```{r}

weighted_mean <- dat %>%
  group_by(year, continent) %>%
  summarize(w_avg = weighted.mean(gdpPercap), population = pop/100000)

 ggplot() +
  geom_point(dat, mapping = aes(x = year, y = gdpPercap, color = continent)) +
  geom_path(dat, mapping = aes(x = year, y = gdpPercap, color = continent)) +
  geom_point(weighted_mean, mapping = aes(x = year, y = w_avg, size = population)) +
  facet_wrap(~continent, nrow = 2) +
  xlab("Year") + ylab("GDP Per Capita") +
  scale_size_continuous(name = "Population (100k)") +
  theme_bw()

```

