---
title: "Task 20"
author: "Claire Hays"
date: "11/14/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
library(lubridate)
library(ggplot2)
library(grid)
library(corrplot)
library(readr) 
library(haven)
library(readxl)
library(foreign)
library(stringr)
library(stringi)
library(tidyquant)
library(timetk)
library(DT)
library(dygraphs)
library(sf)
library(USAboundaries)
library(USAboundariesData)
library(ggsflabel)
library(maps)
library(leaflet)
library(mapview)
```

```{r base_map}
states <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
idaho <- us_counties(states = "ID")

map <- ggplot() +
  geom_sf(data = states, fill = NA) +
  geom_sf(data = idaho, fill = NA) +
  theme_bw() +
  labs(x= ' ',
       y = ' ')
map
```

```{r order_cities}
cities <- us_cities()

population <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii') %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)

one <- population %>%
  slice(1:1)
two <- population %>%
  slice(2:2)
three <- population %>%
  slice(3:3) 
```

```{r add cities to INTERACTIVE graph}

map2 <- map + geom_sf_label(data = one, aes(label = city), color = 'darkblue', size = 2)

interactive_map <- map2 %>% leaflet() %>% addTiles() %>%
  addCircleMarkers(
    data = three,
    color = "lightblue",
    fillOpacity = 1,
    radius = 2,
    label = ~city) %>%  
  addCircleMarkers(
    data = two,
    color = "blue",
    fillOpacity = 1,
    radius = 2,
    label = ~city) %>% 
  addCircleMarkers(
    data = one,
    color = "darkblue",
    fillOpacity = 1,
    radius = 2,
    label = ~city) %>%
  addMarkers(data = one,
             popup = ~as.character(population),
             label = ~city)

interactive_map
```
